global:
  scrape_interval:   15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'blackbox'
    metrics_path: /metrics
    static_configs:
      - targets: ['blackbox-exporter:9115']
  - job_name: 'temperature-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.111:8080']

  - job_name: 'weather-app-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://temperature-app:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
